service:
  name: ts-lambda-template

provider:
  name: aws
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'eu-west-1'}
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB

custom:

functions:
  status:
    handler: dist/handlers/status.lambda
    browserify:
      entries:
        - dist/handlers/status.js
    events:
      - http:
          method: get
          path: status

plugins:
  - serverless-plugin-browserifier
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true