Resources:
  TestEntity:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.database.testEntityTableName}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: TRUE